### ISSUE TITLE
import: unable to load module `/usr/lib/ImageMagick-6.9.5

### ISSUE THREAD

**Issue by egyshell** [AC130USpectre/VKDownloader#1]
![screenshot_2016-09-15_06-11-06](https://cloud.githubusercontent.com/assets/14347603/18536114/458e5f22-7b0b-11e6-8b51-5e2b100b1279.png)

how i can fix this

**Comment by AC130USpectre** [comment]
First, let me notice that the program isn't work anyway, I have to write there more program code.
To your question: it uses module **PyQt4**. Please check that this module is available on your computer. Also, as I work under Windows, as newline symbol I use "\r\n", but on Unix it is just "\n". It may be also the reason of another errors.
